# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      cairo:
        patterns:
          - "cairo-lang-*"
      non critical:
        patterns:
          - "*"
        exclude-patterns:
          - "cairo-lang-*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
