name: Feature Request
description: Suggest an idea for enhancing Cairo language linter.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a 🙋 feature request! 😄

        In case of a relatively big feature that needs feedback from the community, [the cairo-lint Telegram channel][tg] is the best fit.

        [tg]: https://t.me/cairolint
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: >
        Please provide a clear description of your use case and the problem
        this feature request is trying to solve.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: >
        Please provide a clear and concise description of what you want to happen.
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Provide any additional context or information that might be helpful.
