pub mod bool_comparison;
pub mod breaks;
pub mod collapsible_if_else;
pub mod double_comparison;
pub mod double_parens;
pub mod duplicate_underscore_args;
pub mod erasing_op;
pub mod loops;
pub mod single_match;
