pub mod bool_comparison;
pub mod breaks;
pub mod double_comparison;
pub mod double_parens;
pub mod duplicate_underscore_args;
pub mod ifs;
pub mod loops;
pub mod single_match;
pub mod bool_assert_comparison;
