[package]
name = "cairo-lint-dev"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
license-file.workspace = true

[dependencies]

[[bin]]
name = "create_test"
path = "src/main.rs"